CREATE DATABASE $DB_NAME;
CREATE USER $DB_USER@'%' IDENTIFIED BY $DB_PASSWORD;
GRANT ALL PRIVILEGES ON wordpress.* TO $DB_USER@'%';
CREATE USER $WP_USER@'%' IDENTIFIED BY $WP_PASSWORD;
GRANT SHOW DATABASES ON wordpress.* TO $WP_USER@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY '4242';